'use strict';
let token, imageInfo=null, image=null, points=[], prepared=null;
const $=id=>document.getElementById(id);
const groups={
'device-fields':[['sensor','Sensor (os04c10 / ar0231 / ox03c10)'],['unit','Opaque device ID'],['hardware_sha','Hardware evidence SHA'],['operator','Opaque operator ID'],['timestamp','Observation UTC timestamp (YYYY-MM-DDTHH:MM:SSZ)']],
'height-fields':[['height1','Height 1 (m)'],['height2','Height 2 (m)'],['height3','Height 3 (m)'],['height_bound_m','Conservative height absolute bound (m)'],['height_sha','Height / instrument evidence SHA'],['ground_slope_bound_deg','Surveyed ground slope bound (deg)'],['ground_sha','Ground survey evidence SHA']],
'target-fields':[['target_width_m','Measured inner-corner width (m)'],['target_height_m','Measured inner-corner height (m)'],['target_dimension_bound_m','Dimension absolute bound (m)'],['target_planarity_bound_m','Board planarity bound (m)'],['target_sha','Measured target evidence SHA'],['target_x_m','Target origin X (m)'],['target_y_m','Target origin Y (m)'],['target_z_m','Target origin Z (m)'],['target_roll_deg','Target survey roll (deg)'],['target_pitch_deg','Target survey pitch (deg)'],['target_yaw_deg','Target survey yaw (deg)'],['placement_x_bound_m','Placement X bound (m)'],['placement_y_bound_m','Placement Y bound (m)'],['placement_z_bound_m','Placement Z bound (m)'],['placement_roll_bound_deg','Placement roll bound (deg)'],['placement_pitch_bound_deg','Placement pitch bound (deg)'],['placement_yaw_bound_deg','Placement yaw bound (deg)'],['placement_sha','Placement / level / datum evidence SHA'],['corner_bound_px','Observed corner per-axis bound (px)']]};
for(const [group,fields] of Object.entries(groups))for(const [id,text] of fields){
const label=document.createElement('label');label.textContent=text;const input=document.createElement('input');input.id=id;input.autocomplete='off';label.append(input);$(group).append(label);}
async function api(path,data,binary=false){const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':binary?'application/octet-stream':'application/json','X-Target-Token':token},body:data===undefined?undefined:binary?data:JSON.stringify(data)});const x=await r.json();if(!r.ok)throw Error(x.error);return x;}
function draft(){const fields={ack:$('ack').checked};for(const list of Object.values(groups))for(const [id] of list)fields[id]=$(id).value;return {fields,points,image:imageInfo};}
function render(){if(!image)return;const c=$('canvas');c.width=imageInfo.width;c.height=imageInfo.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);ctx.fillStyle='#ff3040';ctx.font='20px sans-serif';points.forEach(([x,y],i)=>{ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.fillText(String(i+1),x+7,y);});$('points').textContent=JSON.stringify(points);}
async function loadImage(info){imageInfo=info;image=new Image();await new Promise((ok,no)=>{image.onload=ok;image.onerror=no;image.src='/image/'+info.sha256;});$('image-info').textContent=info.width+' × '+info.height+' / '+info.sha256;render();}
function invalidate(){prepared=null;$('freeze').disabled=true;}
async function restore(state){invalidate();if(!state.draft)return;const d=state.draft;for(const [id,value] of Object.entries(d.fields||{})){if(id==='ack')$('ack').checked=value===true;else if($(id))$(id).value=value;}points=d.points||[];if(d.image)await loadImage(d.image);}
function action(fn){return async()=>{try{await fn();}catch(e){$('status').textContent=e.message;$('result').textContent=e.message;}};}
document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{for(let n=0;n<5;n++)$('stage'+n).hidden=n!==Number(b.dataset.stage);});
$('canvas').onclick=e=>{if(!image||points.length>=6)return;const r=e.target.getBoundingClientRect();points.push([(e.clientX-r.left)*imageInfo.width/r.width,(e.clientY-r.top)*imageInfo.height/r.height]);prepared=null;$('freeze').disabled=true;render();};
$('undo').onclick=()=>{points.pop();prepared=null;$('freeze').disabled=true;render();};$('clear').onclick=()=>{points=[];prepared=null;$('freeze').disabled=true;render();};
document.addEventListener('input',()=>{prepared=null;$('freeze').disabled=true;});
$('image-file').onchange=action(async()=>{invalidate();const f=$('image-file').files[0];if(!f)return;const x=await api('/api/image',await f.arrayBuffer(),true);points=[];await loadImage(x);});
$('evidence-file').onchange=action(async()=>{const f=$('evidence-file').files[0];if(!f)return;const x=await api('/api/evidence',await f.arrayBuffer(),true);$('evidence-hash').textContent=x.sha256;});
$('save').onclick=action(async()=>{await api('/api/draft',draft());$('status').textContent='Draft saved locally / measurement pending';});
$('reload').onclick=action(async()=>{invalidate();await restore(await api('/api/state'));$('status').textContent='Draft restored';});
$('solve').onclick=action(async()=>{invalidate();const snapshot=JSON.stringify(draft());const input=await api('/api/prepare',JSON.parse(snapshot));const x=await api('/api/solve',input);if(snapshot!==JSON.stringify(draft()))throw Error('Observations changed during solve; repeat preview');prepared=input;$('result').textContent=JSON.stringify(x,null,2);$('freeze').disabled=false;});
$('freeze').onclick=action(async()=>{if(!prepared)throw Error('Preview required');const x=await api('/api/freeze',prepared);$('result').textContent=JSON.stringify(x,null,2);$('freeze').disabled=true;prepared=null;$('status').textContent='Immutable local capture saved; independent validation PENDING';});
(async()=>{try{const cfg=await api('/api/config');token=cfg.token;await restore(cfg.state);window.targetReady=true;}catch(e){$('status').textContent=e.message;}})();
