"""Native MPC/planner + LongControl feedback parity; generic synthetic only.

No sockets, Params, real logs, vehicle controller or device access. These tests
do not execute model inference, radard or a coupled-process replay.
"""
from collections import deque
import math
import unittest

from opendbc.car.interfaces import ACCEL_MIN, ACCEL_MAX
from openpilot.common.realtime import DT_CTRL, DT_MDL
from openpilot.selfdrive.controls.lib.cyber_long.types import CyberLongConfig, CyberLongMode
from openpilot.selfdrive.controls.lib.longcontrol import LongControl
from openpilot.selfdrive.controls.lib.longitudinal_planner import LongitudinalPlanner
from openpilot.selfdrive.controls.tests.test_cyber_long_integration import FixtureSubMaster, car_params, load_baseline


def simulate(scenario, planner_type=LongitudinalPlanner, control_type=LongControl, *, mode=None, feedback=True):
  """Fresh in-process controllers and generic feedback plant for each test arm.

  Six-second scenarios: planner 20 Hz, control/plant 100 Hz. One plant-owned
  30 ms delay and 200 ms response lag are synthetic fixture choices, not vehicle
  calibration. CP's 200 ms planner compensation is not another physical queue.
  """
  if scenario not in ('lead_transition', 'stop_start', 'driver_cancel') or mode not in (None, 'disabled', 'observer'):
    raise ValueError('UNDECLARED_FEEDBACK_FIXTURE')
  cp = car_params()  # Existing explicit SYNTHETIC_PARITY_ONLY contract, not device CP.
  # A crawl allows the declared three-second stopping interval to include true
  # standstill. Starting at 2 m/s tested a moving stopping→PID transition only.
  speed = initial_speed = .5 if scenario == 'stop_start' else 10.
  options = {} if mode is None else {'cyber_long_config': CyberLongConfig(
    mode=CyberLongMode.OBSERVE_ONLY if mode == 'observer' else CyberLongMode.DISABLED)}
  planner = planner_type(cp, init_v=speed, **options)
  control = control_type(cp)
  sm = FixtureSubMaster()
  delay = deque([0.] * 3)
  accel, response, position = 0., 0., 0.
  lead_position = 6. if scenario == 'stop_start' else 35.
  trace = []
  observations = updates = 0
  planner_stride = round(DT_MDL / DT_CTRL)
  assert planner_stride == 5
  for tick in range(600):
    active = not (scenario == 'driver_cancel' and 200 <= tick < 300)
    stopping = scenario == 'stop_start' and tick < 300
    lead_speed = (0. if stopping else 4.) if scenario == 'stop_start' else (10. if tick < 200 else 6.)
    if scenario == 'lead_transition' and tick == 200:
      lead_position = position + 12.  # Declared exogenous cut-in, not generated by a candidate.
    car = sm['carState']
    car.vEgo = speed if feedback else initial_speed
    car.aEgo = accel if feedback else 0.
    car.standstill = car.vEgo < .01
    car.cruiseState.standstill = False
    car.brakePressed = not active
    sm['selfdriveState'].enabled = active
    sm['selfdriveState'].experimentalMode = scenario == 'stop_start'
    sm['controlsState'].longControlState = control.long_control_state
    sm['carControl'].longActive = active
    if tick % planner_stride == 0:
      for service in sm.logMonoTime:
        sm.logMonoTime[service] = (tick + 1) * round(DT_CTRL * 1e9)
      lead = sm['radarState'].leadOne
      lead.present = not (scenario == 'lead_transition' and tick >= 350)
      lead.dRel = max(0., lead_position - position)
      lead.vLead = lead.vLeadK = lead_speed
      lead.vRel = lead_speed - car.vEgo
      lead.aLeadK, lead.aLeadTau, lead.modelProb = 0., 1.5, 1.
      action = sm['modelV2'].action
      action.desiredAcceleration = -.5 if stopping else .2
      action.shouldStop = stopping
      planner.update(sm)
      updates += 1
      policy = getattr(planner, 'cyber_long_policy', None)
      if policy is not None and policy.last_observation is not None:
        observations += 1
    command = float(control.update(active, car, planner.output_a_target, planner.output_should_stop, (ACCEL_MIN, ACCEL_MAX)))
    applied = delay.popleft()
    delay.append(command)
    response += DT_CTRL / .2 * (applied - response)
    next_speed = max(0., speed + response * DT_CTRL)
    accel = (next_speed - speed) / DT_CTRL
    position += .5 * (speed + next_speed) * DT_CTRL
    speed = next_speed
    lead_position += lead_speed * DT_CTRL
    assert all(math.isfinite(v) for v in (command, speed, accel, position))
    assert ACCEL_MIN <= command <= ACCEL_MAX
    trace.append((planner.output_a_target, planner.output_should_stop, command, speed, accel, position,
                  str(control.long_control_state), control.pid.i, planner.mpc.source,
                  tuple(planner.a_desired_trajectory), tuple(planner.mpc.a_solution)))
  return {'trace': tuple(trace), 'planner_updates': updates, 'observations': observations, 'vehicle_qualified': False}


class TestCyberLongFeedback(unittest.TestCase):
  @classmethod
  def setUpClass(cls):
    cls.baseline = load_baseline()
    cls.baseline_control = load_baseline('longcontrol.py')

  def test_independent_closed_loops_preserve_native_baseline_and_observer_parity(self):
    for scenario in ('lead_transition', 'stop_start', 'driver_cancel'):
      with self.subTest(scenario=scenario):
        reference = simulate(scenario, self.baseline.LongitudinalPlanner, self.baseline_control.LongControl)
        repeat = simulate(scenario, self.baseline.LongitudinalPlanner, self.baseline_control.LongControl)
        disabled = simulate(scenario, mode='disabled')
        observer = simulate(scenario, mode='observer')
        self.assertEqual(reference['trace'], repeat['trace'])
        self.assertEqual(reference['trace'], disabled['trace'])
        self.assertEqual(reference['trace'], observer['trace'])
        self.assertEqual(reference['planner_updates'], 120)
        self.assertEqual(len(reference['trace']), 600)
        # Native longControlState starts OFF: the initial planner tick resets.
        # Cancel adds 20 inactive ticks and one OFF-state re-engagement tick.
        self.assertEqual(observer['observations'], 119 if scenario != 'driver_cancel' else 98)
        self.assertEqual(disabled['observations'], 0)
        self.assertFalse(observer['vehicle_qualified'])

  def test_feedback_is_consumed_and_driver_cancel_clears_requested_acceleration(self):
    feedback = simulate('lead_transition')
    disconnected = simulate('lead_transition', feedback=False)
    self.assertNotEqual(feedback['trace'], disconnected['trace'])
    # Planner targets, not only the generic plant state, must respond to feedback.
    self.assertNotEqual([row[0] for row in feedback['trace']], [row[0] for row in disconnected['trace']])
    cancelled = simulate('driver_cancel')
    self.assertTrue(all(row[2] == 0. for row in cancelled['trace'][200:300]))

  def test_stop_start_fixture_reaches_standstill_before_resuming_motion(self):
    stopped = simulate('stop_start')
    self.assertEqual(min(row[3] for row in stopped['trace'][:300]), 0.)
    self.assertGreater(stopped['trace'][-1][3], .1)
